//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlowManagement.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assets()
        {
            this.Assets1 = new HashSet<Assets>();
            this.History = new HashSet<History>();
            this.Incomes1 = new HashSet<Incomes>();
            this.Liabilities = new HashSet<Liabilities>();
            this.StockTransactions = new HashSet<StockTransactions>();
            this.StockTransactions1 = new HashSet<StockTransactions>();
        }
    
        public int Id { get; set; }
        public string AssetName { get; set; }
        public double Value { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DisabledDate { get; set; }
        public string CreatedBy { get; set; }
        public string DisabledBy { get; set; }
        public string ParticipantBank { get; set; }
        public string Note { get; set; }
        public int AssetType { get; set; }
        public string Username { get; set; }
        public Nullable<int> ObtainedBy { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> CashId { get; set; }
        public Nullable<int> IncomeId { get; set; }
        public Nullable<int> ExpenseId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assets> Assets1 { get; set; }
        public virtual Assets Assets2 { get; set; }
        public virtual Incomes Incomes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incomes> Incomes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liabilities> Liabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransactions> StockTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransactions> StockTransactions1 { get; set; }
        public virtual Expenses Expenses { get; set; }
    }
}
