//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlowManagement.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessIncomes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessIncomes()
        {
            this.BusinessLoan = new HashSet<BusinessLoan>();
        }
    
        public int Id { get; set; }
        public string Source { get; set; }
        public double Income { get; set; }
        public double CapitalValue { get; set; }
        public double LoanValue { get; set; }
        public double ExpenseInterest { get; set; }
        public string ParticipantBank { get; set; }
        public string Note { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> DisabledDate { get; set; }
        public string Username { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessLoan> BusinessLoan { get; set; }
    }
}
