//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlowManagement.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessLoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessLoan()
        {
            this.BusinessLoan1 = new HashSet<BusinessLoan>();
        }
    
        public int Id { get; set; }
        public string Source { get; set; }
        public double MortgageValue { get; set; }
        public int InterestType { get; set; }
        public double InterestRatePerYear { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DisabledDate { get; set; }
        public int BusinessId { get; set; }
        public Nullable<int> ParentLoanId { get; set; }
    
        public virtual BusinessIncomes BusinessIncomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessLoan> BusinessLoan1 { get; set; }
        public virtual BusinessLoan BusinessLoan2 { get; set; }
    }
}
